[package]
name = "vide_ffmpeg"
version = "0.1.0"
edition = "2021"

[dependencies]
vide_common = { path = "../vide_common" }
vide_render = { path = "../vide_render" }
ac-ffmpeg = "0.18.1"
wgpu = "23.0.0"
log = "0.4.22"
